name: Build and Deploy Node.js App to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4

      - name: "Set up Node.js version"
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: "Install dependencies"
        run: npm install

      - name: "Build the project"
        run: npm run build --if-present

      - name: "Azure Web App Deploy"
        uses: azure/webapps-deploy@v2
        with:
          app-name: "CloudProjectManagerWeb"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_FF677AC0ECB14AD78E54FDE7EB9E1250 }}
          package: "."
